import pandas as pd
import matplotlib.pyplot as plt
import uuid
from pathlib import Path
from typing import Optional, Dict

def generate_and_save_plot(params: Dict[str, str]) -> Optional[str]:
    """
    Generates a plot using matplotlib based on parameters and saves it to disk.
    Returns the absolute path to the saved plot, or None if it fails.
    """
    dataset_files_str = params.get("dataset") or params.get("csv") # Fallback to csv if generated by older prompt
    x_col = params.get("x_col")
    y_col = params.get("y_col")
    title = params.get("title", f"{y_col} vs {x_col}")
    labels_str = params.get("labels", "")
    
    color_col = params.get("color_col")
    static_color = params.get("color", "tab:blue")
    plot_type = params.get("plot_type", "line").lower()
    invert_y = params.get("invert_y", "false").lower() == "true"
    
    if not (dataset_files_str and x_col and y_col):
        return None
        
    dataset_files = [c.strip() for c in dataset_files_str.split(",")]
    labels = [l.strip() for l in labels_str.split(",")] if labels_str else []
    
    # Pad labels if there are fewer labels than datasets
    while len(labels) < len(dataset_files):
        labels.append(f"Dataset {len(labels)+1}")
        
    try:
        from streamlit_utils.data_utils import load_netcdf, load_csv
        fig, ax = plt.subplots(figsize=(10, 5))
        plotted_any = False
        
        # Color cycle for multiple datasets if static_color isn't strictly meant for a single one
        colors = plt.cm.tab10.colors
        
        for idx, ds_file in enumerate(dataset_files):
            # Load dataset
            if ds_file.endswith(".nc"):
                try:
                    ds = load_netcdf(ds_file)
                    print(f"Loaded NC file: {ds_file}")
                    print(f"Variables present: {list(ds.variables.keys())}")
                    print(f"Checking for x_col='{x_col}', y_col='{y_col}'")
                except Exception as e:
                    print(f"Failed to load NC {ds_file}: {e}")
                    continue
                
                if x_col not in ds.variables or y_col not in ds.variables:
                    print(f"Missing columns! x_col present: {x_col in ds.variables}, y_col present: {y_col in ds.variables}")
                    continue
                
                # Extract only what we need to memory
                cols_to_extract = [x_col, y_col]
                if color_col and color_col in ds.variables:
                    cols_to_extract.append(color_col)
                df = ds[cols_to_extract].to_dataframe().reset_index()
            else:
                df = load_csv(ds_file)
                if x_col not in df.columns or y_col not in df.columns:
                    continue
                
            plotted_any = True
            label = labels[idx]
            
            # Handle datetimes and resampling
            if x_col == "time" or "time" in x_col.lower():
                try:
                    df[x_col] = pd.to_datetime(df[x_col])
                    
                    # Performance optimization: Downsample massive time series
                    if len(df) > 10000:
                        span = df[x_col].max() - df[x_col].min()
                        df.set_index(x_col, inplace=True)
                        
                        # Use numeric_only=True to avoid errors on string columns during mean()
                        if span.days > 180:
                            df = df.resample('D').mean(numeric_only=True)
                        else:
                            df = df.resample('1h').mean(numeric_only=True)
                            
                        df.reset_index(inplace=True)
                except Exception as e:
                    pass
            
            current_color = static_color if len(dataset_files) == 1 else colors[idx % len(colors)]
            
            # Plotting
            if plot_type == "scatter" or color_col:
                if color_col and color_col in df.columns:
                    sc = ax.scatter(df[x_col], df[y_col], c=df[color_col], cmap="viridis", s=10, alpha=0.8, label=label)
                    if idx == 0:  # Only one colorbar to avoid clutter
                        cbar = plt.colorbar(sc, ax=ax)
                        cbar.set_label(color_col)
                else:
                    ax.scatter(df[x_col], df[y_col], color=current_color, s=10, alpha=0.8, label=label)
            else:
                ax.plot(df[x_col], df[y_col], marker='.', linestyle='-', linewidth=0.5, markersize=2, color=current_color, label=label)
        
        if not plotted_any:
            plt.close(fig)
            return None
            
        # Add legend if multiple datasets
        if len(dataset_files) > 1:
            ax.legend()
            
        # Apply custom limits if provided
        if params.get("x_min") is not None and params.get("x_max") is not None:
            try:
                if x_col == "time" or "time" in x_col.lower():
                    ax.set_xlim(pd.to_datetime(params["x_min"]), pd.to_datetime(params["x_max"]))
                else:
                    ax.set_xlim(float(params["x_min"]), float(params["x_max"]))
            except Exception:
                pass
        if params.get("y_min") is not None and params.get("y_max") is not None:
            try:
                ax.set_ylim(float(params["y_min"]), float(params["y_max"]))
            except Exception:
                pass
            
        # Invert Y axis if requested (e.g., for depth/pressure)
        if invert_y:
            ax.invert_yaxis()
            
        ax.set_xlabel(x_col)
        ax.set_ylabel(y_col)
        ax.set_title(title)
        ax.grid(True, linestyle=':', alpha=0.6)
        fig.tight_layout()
        
        force_plot_path = params.get("force_plot_path")
        if force_plot_path:
            plot_path = Path(force_plot_path)
            plot_dir = plot_path.parent
            plot_dir.mkdir(parents=True, exist_ok=True)
        else:
            # We save it into the dir of the first dataset
            plot_dir = Path(dataset_files[0]).parent.parent / "plots"
            plot_dir.mkdir(parents=True, exist_ok=True)
            plot_name = f"plot_{uuid.uuid4().hex[:8]}.png"
            plot_path = plot_dir / plot_name
            
        fig.savefig(plot_path, dpi=150)
        plt.close(fig)
        
        return str(plot_path)
    except Exception:
        return None
